name: Github Pages
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
      - beta
      - test

jobs:
  beta:
    if: contains(github.event.head_commit.message, '[beta]') || contains(github.event.head_commit.message, '[all]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies & build
        env:
          NEXT_PUBLIC_ENV: "beta"
        run: |
          pnpm install --frozen-lockfile    
          pnpm build

      - name: Deploy Gh-Pages 🚀
        uses: XueMoMo/actions-gh-pages@v4.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: beta.dashboard.enreach.network
  staging:
    if: contains(github.event.head_commit.message, '[staging]') || contains(github.event.head_commit.message, '[all]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies & build
        env:
          NEXT_PUBLIC_ENV: "staging"
        run: |
          pnpm install --frozen-lockfile    
          pnpm build

      - name: Deploy Gh-Pages 🚀
        uses: XueMoMo/actions-gh-pages@v4.0.1
        with:
          deploy_key: ${{ secrets.DK_STAGING }}
          publish_dir: ./out
          external_repository: EnReachNetwork/dashboard-site-staging
          cname: staging.dashboard.enreach.network
  prod:
    if: contains(github.event.head_commit.message, '[prod]') || contains(github.event.head_commit.message, '[all]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies & build
        env:
          NEXT_PUBLIC_ENV: "prod"
        run: |
          pnpm install --frozen-lockfile    
          pnpm build

      - name: Deploy Gh-Pages 🚀
        uses: XueMoMo/actions-gh-pages@v4.0.1
        with:
          deploy_key: ${{ secrets.DK_PROD }}
          publish_dir: ./out
          external_repository: EnReachNetwork/dashboard-site-prod
          cname: dashboard.enreach.network
